#!/usr/bin/env dotnet-script
// .claude/hooks/10-log-mistake.csx
// Event: onAgentError (any hook/tool failure payload from Cursor)
// Purpose: capture the error in the `mistakes` table AND emit a stub
//          .github/Lessons/YYYY-MM-DD-<slug>.md pre-filled with the template from
//          .github/agents/dotnet-self-learning-architect.agent.md.
//
// Payload: Cursor delivers the error context on stdin as JSON. We tolerate
// plaintext too (just store whatever we got).

#load "../lib/ContextDb.csx"

using System;
using System.IO;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

try
{
    var stdin = Console.IsInputRedirected ? Console.In.ReadToEnd() : "";
    string agent = "unknown", category = "other", summary = stdin.Trim(), rootCause = "", fix = "";

    if (!string.IsNullOrWhiteSpace(stdin))
    {
        try
        {
            using var doc = JsonDocument.Parse(stdin);
            var root = doc.RootElement;
            if (root.TryGetProperty("agent", out var a))     agent = a.GetString() ?? agent;
            if (root.TryGetProperty("category", out var c))  category = c.GetString() ?? category;
            if (root.TryGetProperty("summary", out var s))   summary = s.GetString() ?? summary;
            if (root.TryGetProperty("rootCause", out var rc)) rootCause = rc.GetString() ?? rootCause;
            if (root.TryGetProperty("error", out var e))     summary = e.GetString() ?? summary;
            if (root.TryGetProperty("tool", out var t))      agent = a.ValueKind == JsonValueKind.Undefined ? (t.GetString() ?? agent) : agent;
        }
        catch { /* fall through — summary already populated from raw stdin */ }
    }

    if (string.IsNullOrWhiteSpace(summary)) summary = "(no summary payload)";

    var slug = MakeSlug(summary, 40);
    var repoRoot = FindRepoRoot();
    var date = DateTime.UtcNow.ToString("yyyy-MM-dd");
    var lessonRel = Path.Combine(".github", "Lessons", $"{date}-{slug}.md");
    var lessonAbs = Path.Combine(repoRoot, lessonRel);
    Directory.CreateDirectory(Path.GetDirectoryName(lessonAbs)!);

    if (!File.Exists(lessonAbs))
    {
        var template = $$"""
        # Lesson: {{summary}}

        ## Metadata
        - PatternId: mediatorlite.lesson.{{slug}}
        - PatternVersion: 1
        - Status: active
        - Supersedes:
        - CreatedAt: {{DateTime.UtcNow:O}}
        - LastValidatedAt:
        - ValidationEvidence:

        ## Task Context
        - Triggering task: (auto-captured from hook payload)
        - Date/time: {{DateTime.UtcNow:O}}
        - Impacted area:
        - Agent: {{agent}}
        - Category: {{category}}

        ## Mistake
        - What went wrong:
        {{Indent(summary)}}
        - Expected behavior:
        - Actual behavior:

        ## Root Cause Analysis
        - Primary cause: {{rootCause}}
        - Contributing factors:
        - Detection gap:

        ## Resolution
        - Fix implemented:
        - Why this fix works:
        - Verification performed:

        ## Preventive Actions
        - Guardrails added:
        - Tests/checks added:
        - Process updates:

        ## Reuse Guidance
        - How to apply this lesson in future tasks:

        ---
        _Generated by `.claude/hooks/10-log-mistake.csx` — please finish filling this in before commit._
        """;
        File.WriteAllText(lessonAbs, template);
    }

    var id = ContextDb.LogMistake(agent, category, summary, rootCause: string.IsNullOrWhiteSpace(rootCause) ? null : rootCause,
                                   fix: string.IsNullOrWhiteSpace(fix) ? null : fix, lessonFile: lessonRel);
    Console.Error.WriteLine($"[hook:10-log-mistake] logged mistake #{id} -> {lessonRel}");
    ContextDb.LogHookEvent("10-log-mistake.csx", "onAgentError", "ok", 0, new { id, agent, category });
}
catch (Exception ex)
{
    Console.Error.WriteLine($"[hook:10-log-mistake] warn: {ex.Message}");
}

static string MakeSlug(string s, int max)
{
    var ascii = Regex.Replace(s.ToLowerInvariant(), "[^a-z0-9]+", "-").Trim('-');
    if (string.IsNullOrEmpty(ascii)) ascii = "untitled";
    return ascii.Length <= max ? ascii : ascii.Substring(0, max).TrimEnd('-');
}

static string Indent(string text) =>
    string.Join('\n', (text ?? "").Split('\n').Select(l => "  " + l));

static string FindRepoRoot()
{
    var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
    while (dir is not null)
    {
        if (Directory.Exists(Path.Combine(dir.FullName, ".git"))) return dir.FullName;
        dir = dir.Parent;
    }
    return Directory.GetCurrentDirectory();
}
